version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 
    commands:
      - echo Installing dependencies...
      - npm install
      - apt-get update && apt-get install -y awscli
  build:
    commands:
      - echo Building frontend application...
      - ng build

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
