version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building frontend application...
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist/frontend-app-for-cf s3://three-tier-frontend-application-bucket

artifacts:
  files:
    - '**/*'
  base-directory: 'dist' 